const songReference = [
  {
    id: 1,
    title: 'Since Then',
    artist: 'P Montana, Sona, Baseman',
    song: '1. Since Then',
    cover: 'since then',
  },
  {
    id: 2,
    title: 'Creep On Me',
    artist: 'Gashi, French Montana, DJ Snake',
    song: '2. Creep on me',
    cover: 'creep on me',
  },
  {
    id: 3,
    title: 'Akhi',
    artist: 'Dree Low',
    song: '3. Akhi',
    cover: 'akhi',
  },
  {
    id: 4,
    title: 'Har du vatt här',
    artist: 'GULEED',
    song: '4. Har du vatt här',
    cover: 'har du vatt här',
  },
  {
    id: 5,
    title: 'Faster Than Fast',
    artist: 'Quada',
    song: '5. Faster than fast',
    cover: 'faster than fast',
  },
  {
    id: 6,
    title: "C'est une frappe",
    artist: 'Lartiste',
    song: "6. C'est une frappe",
    cover: 'cest une frappe',
  },
  {
    id: 7,
    title: 'Vice',
    artist: 'Haval',
    song: '7. Vice',
    cover: 'vice',
  },
  {
    id: 8,
    title: 'Young & Heartless',
    artist: 'Yasin',
    song: '8. Young & Heartless',
    cover: 'young & heartless',
  },
]
